#!/bin/bash


set -e
git_branch() {
    git branch --no-color 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

git_status() {
    local status="$(git status --porcelain 2>/dev/null)"
    local output=''
    [[ -n $(egrep '^[MADRC]' <<<"$status") ]] && output="$output+"
    [[ -n $(egrep '^.[MD]' <<<"$status") ]] && output="$output!"
    [[ -n $(egrep '^\?\?' <<<"$status") ]] && output="$output?"
    [[ -n $(git stash list) ]] && output="${output}S"
    [[ -n $(git log --branches --not --remotes) ]] && output="${output}P"
    [[ -n $output ]] && output="|$output"  # separate from branch name
    echo $output
}

git_color() {
    local staged=$([[ $1 =~ \+ ]] && echo yes)
    local dirty=$([[ $1 =~ [!\?] ]] && echo yes)
    local needs_push=$([[ $1 =~ P ]] && echo yes)
    if [[ -n $staged ]] && [[ -n $dirty ]]; then
        echo -e '\033[1;33m'  # bold yellow
    elif [[ -n $staged ]]; then
        echo -e '\033[1;32m'  
    elif [[ -n $dirty ]]; then
        echo -e '\033[1;31m' 
    elif [[ -n $needs_push ]]; then
        echo -e '\033[1;34m' 
    else
        echo -e '\033[1;37m'
    fi
}

git_prompt() {
    local branch=$(git_branch)
    if [[ -n $branch ]]; then
        local state=$(git_status)
        local color=$(git_color $state)
        echo -e "\x01$color\x02[$branch$state]\x01\033[00m\x02"
    fi
}

now=$(date +%Y-%m-%dT%H:%M:%S%z)
sha=$(git rev-parse --short HEAD)
gstatus=$(git_status);
gcolor=$(git_color);
gbranch=$(git_branch)

echo "\"Deployed\" ${sha}${status} para  ${DEPLOY_STAGE} as  ${now}"

