name: Deploy to Qualidade
on:
  push:
    branches:
    - qualidade
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: CheckOut
      uses: actions/checkout@v4

    - name: ValidaTesteUnitário
      run: scripts/testeunitario

    - name: DeployQualidade
      env:
        DEPLOY_STAGE: qualidade
        DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
      run: scripts/testeunitario
