name: Qualidade to Production

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: checkOuyt
      uses: actions/checkout@v4
      
    - name: TesteUnitario
      run: script/testeunitario
    
    - name: Deployment
      env:
        DEPLOY_STAGE: main
        DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
      run: script/deploy
