name: Qualidade to Production

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Precheck

      run: script/test
    
    - name: Deployment
      env:
        DEPLOY_STAGE: production
        DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
      run: script/deploy